ALTER TABLE Ingredients
	ADD CONSTRAINT IShip FOREIGN KEY (IngShipment_ID) REFERENCES Shipment (Shipment_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Ingredients
	ADD CONSTRAINT IStor FOREIGN KEY (IngStorage_ID) REFERENCES Storage (Storage_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Dish
	ADD CONSTRAINT I1 FOREIGN KEY (Primary_Ingredient) REFERENCES Ingredients (IngName);

ALTER TABLE Dish
	ADD CONSTRAINT I2 FOREIGN KEY (Secondary_Ingredient) REFERENCES Ingredients (IngName);

ALTER TABLE Dish
	ADD CONSTRAINT I3 FOREIGN KEY (Tretiary_Ingredient) REFERENCES Ingredients (IngName);